from pathlib import Path
from typing import Mapping, Protocol, Tuple, runtime_checkable


@runtime_checkable
class FlyConfigPort(Protocol):
    @property
    def app_name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def show_path(self) -> bool: ...

@runtime_checkable
class DomainConfigPort(Protocol):
    @property
    def words_to_remove(self) -> Tuple[str, ...]: ...
    @property
    def statements_types(self) -> Tuple[str, ...]: ...
    @property
    def base_currency(self) -> str: ...
    @property
    def nsd_gap_days(self) -> int: ...

@runtime_checkable
class DatabaseConfigPort(Protocol):
    @property
    def db_filename(self) -> str: ...
    @property
    def connection_string(self) -> str: ...
    @property
    def tables(self) -> Mapping[str, str]: ...

@runtime_checkable
class LoggerConfigPort(Protocol):
    @property
    def log_dir(self) -> Path: ...
    @property
    def log_file_name(self) -> str: ...
    @property
    def level(self) -> str: ...
    @property
    def show_path(self) -> bool: ...

@runtime_checkable
class PathConfigPort(Protocol):
    @property
    def temp_dir(self) -> Path: ...
    @property
    def log_dir(self) -> Path: ...
    @property
    def data_dir(self) -> Path: ...
    @property
    def root_dir(self) -> Path: ...


@runtime_checkable
class WorkerPoolConfig(Protocol):
    @property
    def max_workers(self) -> int: ...
    @propertyH
    def queue_size(self) -> int: ...
    @property
    def persistance_threeshold(self) -> int: ...


@runtime_checkable
class RepositoryConfig(Protocol):
    @property
    def batch_size(self) -> int: ...

@runtime_checkable
class ExchangeApiConfig(Protocol):
    @property
    def language(self) -> str: ...
    @property
    def company_data_endpoint(self) -> Mapping[str, str]: ...
    @property
    def nsd_endpoint(self) -> str: ...

@runtime_checkable
class ConfigPort(Protocol):
    @property
    def fly_settings(self) -> FlyConfigPort: ...
    @property
    def domain(self) -> DomainConfigPort: ...
    @property
    def database(self) -> DatabaseConfigPort: ...
    @property
    def logging(self) -> LoggerConfigPort: ...
    @property
    def paths(self) -> PathConfigPort: ...
    @property
    def worker_pool(self) -> WorkerPoolConfig: ...
    @property
    def repository(self) -> RepositoryConfig: ...
    @property
    def exchange(self) -> ExchangeApiConfig: ...
