export const COMPANY_FACETS = [
  // --- Campos textuais SINGLE -----------------------------------------------------
  {
    key: 'industry_sector',
    field: 'industry_sector',
    label: 'Setor',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'industry_subsector',
    field: 'industry_subsector',
    label: 'Subsetor',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'industry_segment',
    field: 'industry_segment',
    label: 'Segmento',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'listingSegment',
    field: 'listing_segment',
    label: 'Segmento de Listagem',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'company_name',
    field: 'company_name',
    label: 'Companhia',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'trading_name',
    field: 'trading_name',
    label: 'Nome de Pregão',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'issuing_company',
    field: 'issuing_company',
    label: 'Código',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'code',
    field: 'code',
    label: 'Ticker',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'cnpj',
    field: 'cnpj',
    label: 'CNPJ',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'market',
    field: 'market',
    label: 'Mercado',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'institution_common',
    field: 'institution_common',
    label: 'Instituição Ordinária',
    type: 'select',
    multiple: true,
    searchable: true,
  },
  {
    key: 'institution_preferred',
    field: 'institution_preferred',
    label: 'Instituição Preferencial',
    type: 'select',
    multiple: true,
    searchable: true,
  },
]
